  ; ===========================================
  ; d3dpmesh.inc copyright MASM32 1998 - 2005
  ; ===========================================

IFNDEF D3DPMESH_INC
D3DPMESH_INC equ <1>

CreateD3DRMPMeshVisual PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD

ELSE
echo -----------------------------------------
echo WARNING Duplicate include file d3dpmesh.inc
echo -----------------------------------------
ENDIF
