  ; ===========================================
  ; nia35det.inc copyright MASM32 1998 - 2005
  ; ===========================================

IFNDEF NIA35DET_INC
NIA35DET_INC equ <1>

FindAdapterHandler PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD

ELSE
echo -----------------------------------------
echo WARNING Duplicate include file nia35det.inc
echo -----------------------------------------
ENDIF
